import { Project, Tag, Task, UserProfile } from '../types';

export const mockUser: UserProfile = {
  id: 'usr_student_01',
  name: 'Alex Rivera',
  email: 'alex.rivera@university.edu',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  role: 'CS Undergrad & Full-Stack Dev',
};

export const mockProjects: Project[] = [
  {
    id: 'proj_college',
    name: 'College',
    color: '#6366f1', // Indigo
    description: 'Coursework, lectures, assignments, and exam preparation',
  },
  {
    id: 'proj_personal',
    name: 'Personal',
    color: '#10b981', // Emerald
    description: 'Health, habits, finances, and personal errands',
  },
  {
    id: 'proj_projects',
    name: 'Projects',
    color: '#f59e0b', // Amber
    description: 'Software projects, open-source repositories, and portfolio',
  },
];

export const mockTags: Tag[] = [
  { id: 'tag_dev', name: 'Development', color: '#3b82f6' },
  { id: 'tag_study', name: 'Study', color: '#8b5cf6' },
  { id: 'tag_personal', name: 'Personal', color: '#10b981' },
  { id: 'tag_urgent', name: 'Urgent', color: '#ef4444' },
  { id: 'tag_design', name: 'Design', color: '#ec4899' },
  { id: 'tag_docs', name: 'Documentation', color: '#64748b' },
];

const todayStr = new Date().toISOString().split('T')[0];

const tomorrowDate = new Date();
tomorrowDate.setDate(tomorrowDate.getDate() + 1);
const tomorrowStr = tomorrowDate.toISOString().split('T')[0];

const nextWeekDate = new Date();
nextWeekDate.setDate(nextWeekDate.getDate() + 4);
const nextWeekStr = nextWeekDate.toISOString().split('T')[0];

export const initialMockTasks: Task[] = [
  {
    id: 'task_01',
    userId: 'usr_student_01',
    title: 'Complete project documentation for TaskFlow',
    description: 'Write comprehensive technical specs, API schema blueprints, and architecture diagrams for the GitHub submission.',
    status: 'todo',
    priority: 'high',
    projectId: 'proj_college',
    tags: ['Documentation', 'Study'],
    dueDate: todayStr,
    dueTime: '4:00 PM',
    recurrence: 'none',
    subtasks: [
      { id: 'sub_1', title: 'Draft API route table for FastAPI', completed: true },
      { id: 'sub_2', title: 'Detail Firebase Firestore security rules', completed: false },
      { id: 'sub_3', title: 'Export system architecture flowchart', completed: false },
    ],
    createdAt: new Date(Date.now() - 3600000 * 24).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task_02',
    userId: 'usr_student_01',
    title: 'Review GitHub pull requests & test coverage',
    description: 'Check CI pipeline status, verify unit test coverage with Vitest, and merge the frontend shell branch.',
    status: 'todo',
    priority: 'medium',
    projectId: 'proj_projects',
    tags: ['Development'],
    dueDate: todayStr,
    dueTime: '6:30 PM',
    recurrence: 'none',
    createdAt: new Date(Date.now() - 3600000 * 18).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task_03',
    userId: 'usr_student_01',
    title: 'Implement token verification middleware in FastAPI',
    description: 'Validate incoming Bearer tokens using Firebase Admin SDK auth.verify_id_token prior to querying Firestore.',
    status: 'todo',
    priority: 'high',
    projectId: 'proj_projects',
    tags: ['Development', 'Urgent'],
    dueDate: todayStr,
    dueTime: '8:00 PM',
    recurrence: 'none',
    subtasks: [
      { id: 'sub_4', title: 'Install firebase-admin package', completed: true },
      { id: 'sub_5', title: 'Create get_current_user dependency', completed: false },
      { id: 'sub_6', title: 'Add 401 Unauthorized error handling', completed: false },
    ],
    createdAt: new Date(Date.now() - 3600000 * 12).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task_04',
    userId: 'usr_student_01',
    title: 'Prepare presentation slides for Capstone kickoff',
    description: 'Summarize key problem statements, student user personas, and core technical milestones.',
    status: 'completed',
    priority: 'medium',
    projectId: 'proj_college',
    tags: ['Design', 'Study'],
    dueDate: todayStr,
    dueTime: '11:00 AM',
    completedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 36).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task_05',
    userId: 'usr_student_01',
    title: 'Read chapter 4: LSM Trees & Storage Engines',
    description: 'Study the difference between B-Trees and SSTables in modern NoSQL and distributed database architectures.',
    status: 'todo',
    priority: 'low',
    projectId: 'proj_college',
    tags: ['Study'],
    dueDate: todayStr,
    dueTime: '9:30 PM',
    recurrence: 'none',
    createdAt: new Date(Date.now() - 3600000 * 8).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task_06',
    userId: 'usr_student_01',
    title: 'Design responsive Mobile Drawer and Command Palette',
    description: 'Ensure touch targets adhere to 44px minimum and keyboard shortcuts Ctrl+K trigger smoothly.',
    status: 'completed',
    priority: 'high',
    projectId: 'proj_projects',
    tags: ['Development', 'Design'],
    dueDate: todayStr,
    dueTime: '2:00 PM',
    completedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 40).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task_07',
    userId: 'usr_student_01',
    title: 'Order replacement mechanical keyboard switches',
    description: 'Check compatibility with hot-swap PCB and select tactile silent switches for dorm study sessions.',
    status: 'completed',
    priority: 'low',
    projectId: 'proj_personal',
    tags: ['Personal'],
    dueDate: todayStr,
    dueTime: '10:00 AM',
    completedAt: new Date(Date.now() - 3600000 * 6).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 48).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task_08',
    userId: 'usr_student_01',
    title: 'Set up Pytest suite with FastAPI TestClient fixtures',
    description: 'Author unit tests for task validation schemas, unauthorized requests, and project CRUD.',
    status: 'todo',
    priority: 'medium',
    projectId: 'proj_projects',
    tags: ['Development'],
    dueDate: tomorrowStr,
    dueTime: '3:00 PM',
    recurrence: 'none',
    createdAt: new Date(Date.now() - 3600000 * 10).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task_09',
    userId: 'usr_student_01',
    title: 'Submit Distributed Operating Systems milestone 2',
    description: 'Ensure all test vectors pass before tagging release v0.2.0.',
    status: 'todo',
    priority: 'high',
    projectId: 'proj_college',
    tags: ['Study', 'Urgent'],
    dueDate: tomorrowStr,
    dueTime: '11:59 PM',
    recurrence: 'none',
    createdAt: new Date(Date.now() - 3600000 * 14).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task_10',
    userId: 'usr_student_01',
    title: 'Grocery run & meal prep for the exam week',
    description: 'Healthy snacks, oats, fruits, and cold brew coffee.',
    status: 'todo',
    priority: 'low',
    projectId: 'proj_personal',
    tags: ['Personal'],
    dueDate: nextWeekStr,
    dueTime: '12:00 PM',
    recurrence: 'weekly',
    createdAt: new Date(Date.now() - 3600000 * 20).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task_11',
    userId: 'usr_student_01',
    title: 'Renew GitHub Student Developer Pack',
    description: 'Upload current academic enrollment verification document.',
    status: 'completed',
    priority: 'medium',
    projectId: 'proj_personal',
    tags: ['Personal', 'Documentation'],
    dueDate: todayStr,
    completedAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 50).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'task_12',
    userId: 'usr_student_01',
    title: 'Schedule weekly office hours with Dr. Henderson',
    description: 'Discuss distributed consensus algorithms and Paxos vs Raft.',
    status: 'completed',
    priority: 'medium',
    projectId: 'proj_college',
    tags: ['Study'],
    dueDate: todayStr,
    completedAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    createdAt: new Date(Date.now() - 3600000 * 60).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
